### ISSUE TITLE
Protect against undefined action types

### ISSUE THREAD

**Issue by elado** [kolodny/redux-create-reducer#1]
``` js
const actionTypes = {}
createReducer({}, {
  [actionTypes.BLAH](state, action) {

  }
})
```

when `actionTypes.BLAH` is `undefined` because it was mistyped, it'll probably create a lot of unwanted behavior.

To fix that, need to protect agains `'undefined'` keys, with `invariant`.

**Comment by kolodny** [comment]
I'm not sure that's possible without also not letting the string `"undefined"` be used as a key too. Javascript stringifies all hashmap properties

**Comment by elado** [comment]
Yes, I specified `'undefined'` as a string. Sounds very unlikely as an action name though, no?

Redux protects against `undefined` but though the actual variable, so it can use `typeof`.
https://github.com/rackt/redux/blob/master/src%2FcreateStore.js#L129

**Comment by kolodny** [comment]
yeah but this module should not assume that the string `'undefined'` must be a mistake. The linked code actually checks if the variable is undefined or not, and doesn't check if it's equal to the string `'undefined'`

**Comment by elado** [comment]
Yep, I understand it can't really do that. Maybe a `console.warn` only in development mode?

**Comment by elado** [comment]
While one may call an action type `undefined`, 99% of the cases would be a typo.

**Comment by kolodny** [comment]
I can see that being useful. I tend to import each action I'm using `import { BLAH } from 'foo'`  and use https://github.com/dozoisch/babel-plugin-import-asserts but I'm open to a PR that covers `'undefined'`
