### ISSUE TITLE
Use official redux types

### ISSUE THREAD

**Issue by JakeSidSmith** [kolodny/redux-create-reducer#18]
Why are you no longer using the types provided by redux? The types this library now provides do not match that of redux, and are likely to get even more out of sync.

**Comment by kolodny** [comment]
The reducer type from redux doesn't match the reducer type for this library. Once I need some customization with the types I'd rather not mix and match. Furthermore, I can't see redux changing the definition of what an Action is. Doing so would break `NgRx` along with many other libraries so I'm not worried about that happening.
