### ISSUE TITLE
Why a new major version?

### ISSUE THREAD

**Issue by gpbl** [kolodny/redux-create-reducer#19]
I was looking to upgrade to v2 and I couldn't find a changelog – is it going to break from v1? From the commits it seems OK.

Thanks for this package @kolodny!

**Comment by kolodny** [comment]
This was mostly done due to the new typescript typing added to the project. I figured if this was only a minor bump I'd break quite a few folks so I made it a major bump to avoid that. Glad to hear you're enjoying this library! Let me know if you have any further questions.

**Comment by gpbl** [comment]
Thanks @kolodny! Maybe you could [keep a changelog](https://keepachangelog.com) :)
